FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/Pars.Web/Pars.Web.csproj", "src/Pars.Web/"]
RUN dotnet restore "src/Pars.Web/Pars.Web.csproj"

COPY . .
WORKDIR "/src/src/Pars.Web"
RUN dotnet publish "Pars.Web.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Pars.Web.dll"]