namespace Pars.Domain.Entities.Attendance;

public class EmployeeGroup { public long Id { get; set; } public string? Name { get; set; } public string? Description { get; set; } public string? AddBy { get; set; } public ICollection<EmployeeGroupPerson> Persons { get; set; }=new List<EmployeeGroupPerson>(); public ICollection<GroupShiftAssignment> ShiftAssignments { get; set; }=new List<GroupShiftAssignment>(); }
public class EmployeeGroupPerson { public long Id { get; set; } public long GroupId { get; set; } public string PersonId { get; set; }=default!; public string? Date { get; set; } public string? AddBy { get; set; } public EmployeeGroup? Group { get; set; } public Personal? Personal { get; set; } }
public class ShiftType { public int Id { get; set; } public string? Name { get; set; } public string? Caption { get; set; } public ICollection<Shift> Shifts { get; set; }=new List<Shift>(); }
public class Shift { public long Id { get; set; } public string? Name { get; set; } public int? ShiftTypeId { get; set; } public string? ShiftCode { get; set; } public string? Description { get; set; } public string? StartDate { get; set; } public int? CycleDays { get; set; } public int? OvertimeCeiling { get; set; } public string? AddBy { get; set; } public ShiftType? ShiftType { get; set; } public ICollection<ShiftDetail> Details { get; set; }=new List<ShiftDetail>(); }
public class WeekDay { public int Id { get; set; } public int? Index { get; set; } public string? Name { get; set; } public string? Caption { get; set; } public string? Abbreviation { get; set; } }
public class ShiftDetail { public long Id { get; set; } public long ShiftId { get; set; } public string? Description { get; set; } public string? Date { get; set; } public int? WeekDayId { get; set; } public int? ScheduleOrder { get; set; } public TimeSpan? StartTime { get; set; } public int? StartEarlyMin { get; set; } public int? StartLateMin { get; set; } public TimeSpan? EndTime { get; set; } public int? EndEarlyMin { get; set; } public int? EndLateMin { get; set; } public bool? IsOffDay { get; set; } public bool? IsContinuedNextDay { get; set; } public int? OvertimeCeiling { get; set; } public int? FloatDutyMin { get; set; } public string? AddBy { get; set; } public Shift? Shift { get; set; } public WeekDay? WeekDay { get; set; } }
public class GroupShiftAssignment { public long Id { get; set; } public long GroupId { get; set; } public long ShiftId { get; set; } public string? StartDate { get; set; } public string? AddBy { get; set; } public EmployeeGroup? Group { get; set; } public Shift? Shift { get; set; } }
public class ManualAttendanceEntry { public long Id { get; set; } public string PersonId { get; set; }=default!; public string? Kind { get; set; } public string? Date { get; set; } public TimeSpan? Time { get; set; } public string? Description { get; set; } public string? SendTo { get; set; } public string? Status { get; set; } public string? AddBy { get; set; } public string? AddBy2 { get; set; } public Personal? Personal { get; set; } }
public class RequestType { public long Id { get; set; } public string? Category { get; set; } public string? SubCategory { get; set; } public string? AddBy { get; set; } }
public class MissionEntry { public long Id { get; set; } public long? RequestTypeId { get; set; } public string? Code { get; set; } public string PersonId { get; set; }=default!; public string? DateFrom { get; set; } public string? DateTo { get; set; } public TimeSpan? TimeFrom { get; set; } public TimeSpan? TimeTo { get; set; } public string? Destination { get; set; } public string? SubstitutePersonId { get; set; } public bool? HasVehicle { get; set; } public string? Subject { get; set; } public long? VehicleId { get; set; } public string? AddBy { get; set; } public string? Status { get; set; } public string? AddBy2 { get; set; } public long? DriverId { get; set; } public string? ToId { get; set; } public byte[]? Claim { get; set; } public Personal? Personal { get; set; } public RequestType? RequestType { get; set; } }
public class Holiday { public long Id { get; set; } public string? Name { get; set; } public string? Description { get; set; } public string? HolidayDate { get; set; } public int? Year { get; set; } public string? AddBy { get; set; } }
public class WorkCalendarDay { public DateTime Date { get; set; } public string? DayName { get; set; } public string? PersianDate { get; set; } }
public class RequestAllocationCatalogue { public long Id { get; set; } public string? PersonId { get; set; } public long? RequestTypeId { get; set; } public string? Date { get; set; } public int? Year { get; set; } public string? Interval { get; set; } public int? Count { get; set; } public string? AddBy { get; set; } public string? Comment { get; set; } public string? CalculationType { get; set; } public Personal? Personal { get; set; } public RequestType? RequestType { get; set; } }
public class DailyAttendanceCalculation { public string? PersianDate { get; set; } public string? PersonId { get; set; } public int? AttendanceMins { get; set; } public int? DutyAttendanceMins { get; set; } public DateTime? ArrivalDateTime { get; set; } public DateTime? DepartureDateTime { get; set; } public int? ArrivalLateMinutes { get; set; } public int? DepartureEarlyMinutes { get; set; } public string? AttendanceDuration { get; set; } public string? DutyAttendanceDuration { get; set; } public string? DeductionDuration { get; set; } public int? DeductionMins { get; set; } public string? ArrivalPersianDateTime { get; set; } public string? DeparturePersianDateTime { get; set; } public string? ArrivalLateDuration { get; set; } public string? DepartureEarlyDuration { get; set; } public bool? IsContinuedNextDay { get; set; } public long? ShiftDetailId { get; set; } public long? ShiftId { get; set; } public bool? IsOffDay { get; set; } public int? EntriesCount { get; set; } public string? Entries { get; set; } public bool? IsDailyRequest { get; set; } public int? HourlyLeaveRequestMinutes { get; set; } public int? HourlyMissionRequestMinutes { get; set; } public string? Category { get; set; } public string? SubCategory { get; set; } public bool? IsCalendarHoliday { get; set; } public string? HourlyLeaveRequestDuration { get; set; } public string? HourlyMissionRequestDuration { get; set; } public DateTime? StartTime { get; set; } public DateTime? EndTime { get; set; } public string? DayCaption { get; set; } public int? OvertimeDepartureMinute { get; set; } public int? OvertimeArrivalMinute { get; set; } public string? OvertimeDuration { get; set; } public int? OvertimeMinute { get; set; } public string? RequestStatus { get; set; } public string? Status { get; set; } }
