using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Pars.Domain.Entities.Auth;
using Pars.Domain.Entities.Core;
namespace Pars.Infrastructure.Persistence.Configurations.Core;

public sealed class UserConfiguration : IEntityTypeConfiguration<User> { public void Configure(EntityTypeBuilder<User>b){b.ToTable("Users","auth");b.HasKey(x=>x.Id);b.Property(x=>x.Username).HasMaxLength(50).IsRequired();b.HasIndex(x=>x.Username).IsUnique();b.Property(x=>x.PasswordHash).IsRequired();b.Property(x=>x.FirstName).HasMaxLength(50);b.Property(x=>x.LastName).HasMaxLength(50);b.Property(x=>x.Email).HasMaxLength(100);} }
public sealed class RoleConfiguration : IEntityTypeConfiguration<Role> { public void Configure(EntityTypeBuilder<Role>b){b.ToTable("Roles","auth");b.HasKey(x=>x.Id);b.Property(x=>x.Name).HasMaxLength(50).IsRequired();b.HasIndex(x=>x.Name).IsUnique();b.Property(x=>x.Description).HasMaxLength(100);} }
public sealed class UserRoleConfiguration : IEntityTypeConfiguration<UserRole> { public void Configure(EntityTypeBuilder<UserRole>b){b.ToTable("UserRoles","auth");b.HasKey(x=>new{x.UserId,x.RoleId});b.HasOne(x=>x.User).WithMany(x=>x.UserRoles).HasForeignKey(x=>x.UserId).OnDelete(DeleteBehavior.Cascade);b.HasOne(x=>x.Role).WithMany(x=>x.UserRoles).HasForeignKey(x=>x.RoleId).OnDelete(DeleteBehavior.Cascade);} }
public sealed class LegacyMenuConfiguration:IEntityTypeConfiguration<LegacyMenuItem>{public void Configure(EntityTypeBuilder<LegacyMenuItem>b){b.ToTable("tblMenu","dbo");b.HasKey(x=>x.Id);b.Property(x=>x.Id).HasColumnName("id");b.Property(x=>x.Description).HasColumnName("des").HasMaxLength(50);b.Property(x=>x.Price).HasColumnName("price").HasColumnType("numeric(18,0)");b.Property(x=>x.Calories).HasColumnName("caleri").HasColumnType("numeric(18,0)");b.Property(x=>x.Kind).HasColumnName("kind");b.Property(x=>x.AddBy).HasColumnName("addby").HasMaxLength(250);b.Property(x=>x.Days).HasColumnName("ayam").HasMaxLength(250);}}
public sealed class LegacyAccessConfiguration:IEntityTypeConfiguration<LegacyAccess>{public void Configure(EntityTypeBuilder<LegacyAccess>b){b.ToTable("tblDatresi","dbo");b.HasKey(x=>x.FormName);b.Property(x=>x.FormName).HasColumnName("frmname").HasMaxLength(150);b.Property(x=>x.FormDescription).HasColumnName("frmdes").HasMaxLength(250);b.Property(x=>x.EditUsers).HasColumnName("edit1");b.Property(x=>x.ViewUsers).HasColumnName("view1");b.Property(x=>x.ApproveUsers).HasColumnName("approve");b.Property(x=>x.ApproveLevel).HasColumnName("approveLevel");b.Property(x=>x.AddBy).HasColumnName("addby").HasMaxLength(250);b.Property(x=>x.AdminLevel).HasColumnName("adminlevel");b.Property(x=>x.Approve2).HasColumnName("approve2");b.Property(x=>x.Approve3).HasColumnName("approve3");b.Property(x=>x.Approve4).HasColumnName("approve4");b.Property(x=>x.Approve5).HasColumnName("approve5");b.Property(x=>x.DeleteUsers).HasColumnName("Delete1");b.Property(x=>x.DeleteComment).HasColumnName("DeleteComment").HasMaxLength(500);b.Property(x=>x.EditComment).HasColumnName("EditComment").HasMaxLength(500);b.Property(x=>x.A1Comment).HasColumnName("A1Comment").HasMaxLength(500);b.Property(x=>x.A2Comment).HasColumnName("A2Comment").HasMaxLength(500);b.Property(x=>x.A3Comment).HasColumnName("A3Comment").HasMaxLength(500);b.Property(x=>x.A4Comment).HasColumnName("A4Comment").HasMaxLength(500);b.Property(x=>x.A5Comment).HasColumnName("A5Comment").HasMaxLength(500);b.Property(x=>x.Tag).HasColumnName("tag").HasMaxLength(500);}}
public sealed class LegacyAccessScopeConfiguration:IEntityTypeConfiguration<LegacyAccessScope>{public void Configure(EntityTypeBuilder<LegacyAccessScope>b){b.ToTable("tblDatresi_Child","dbo");b.HasKey(x=>x.Id);b.Property(x=>x.Id).HasColumnName("id");b.Property(x=>x.FormName).HasColumnName("frmname").HasMaxLength(150);b.Property(x=>x.Kind).HasColumnName("kind").HasMaxLength(15);b.Property(x=>x.UnitCode).HasColumnName("codeVahed").HasMaxLength(50);b.Property(x=>x.UnitName).HasColumnName("NameVahed").HasMaxLength(150);b.Property(x=>x.Position).HasColumnName("Semat");b.Property(x=>x.AddBy).HasColumnName("addby").HasMaxLength(250);b.Property(x=>x.Status).HasColumnName("Status").HasMaxLength(10);/* FK in legacy documentation points elsewhere, so no assumed relation to tblDatresi. */b.Ignore(x=>x.Access);}}
